[build]
  publish = "./"
  functions = "netlify/functions"

[dev]
  publish = "./"
  functions = "netlify/functions"
  
[functions]
  node_bundler = "esbuild"

[build.environment]
  NODE_VERSION = "18"